name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      - name: hello_world
        run: echo "Hello world"
        shell: bash
  goodbye:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      # - uses: actions/checkout@v4.2.2
      - name: goodbye
        run: echo "Goodbye world"
        shell: bash